name: Bug Report
description: Report a bug in Dendrovia
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please fill out the sections below so we can reproduce and fix the issue.

  - type: dropdown
    id: pillar
    attributes:
      label: Pillar
      description: Which pillar is affected?
      options:
        - CHRONOS (Git History + AST)
        - IMAGINARIUM (Procedural Art)
        - ARCHITECTUS (3D Rendering)
        - LUDUS (Game Mechanics)
        - OCULUS (UI + Navigation)
        - OPERATUS (Infrastructure)
        - Shared / Cross-pillar
        - Unknown
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect to happen?
      placeholder: "When I click X, Y happens instead of Z..."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the bug
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Runtime details
      value: |
        - OS:
        - Browser:
        - Bun version:
        - Node version:
    validations:
      required: false
