name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Describe the feature you'd like to see in Dendrovia.

  - type: dropdown
    id: pillar
    attributes:
      label: Pillar
      description: Which pillar does this relate to?
      options:
        - CHRONOS (Git History + AST)
        - IMAGINARIUM (Procedural Art)
        - ARCHITECTUS (3D Rendering)
        - LUDUS (Game Mechanics)
        - OCULUS (UI + Navigation)
        - OPERATUS (Infrastructure)
        - Cross-pillar / Architecture
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What would you like to see?
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this useful? What problem does it solve?
    validations:
      required: false
