// ============================================================
// DENDROVIA Raymarcher — Generated by IMAGINARIUM
// Seed: {{SEED}}
// Variant: {{VARIANT_ID}}
// ============================================================

precision highp float;

uniform float time;
uniform vec2 resolution;
{{COLOR_UNIFORMS}}

// --- SDF Library ---
{{SDF_LIBRARY}}

// --- Scene Definition ---
{{SCENE_SDF}}

// --- Lighting ---
{{LIGHTING}}

// --- Raymarching ---
void main() {
  vec2 uv = (gl_FragCoord.xy - 0.5 * resolution.xy) / resolution.y;

  // Camera
  vec3 ro = vec3(0.0, 2.5, -5.0);
  vec3 ta = vec3(0.0, 2.0, 0.0);
  vec3 ww = normalize(ta - ro);
  vec3 uu = normalize(cross(ww, vec3(0.0, 1.0, 0.0)));
  vec3 vv = cross(uu, ww);
  vec3 rd = normalize(uv.x * uu + uv.y * vv + 1.8 * ww);

  // March
  float t = 0.0;
  float d;
  for (int i = 0; i < 96; i++) {
    vec3 p = ro + rd * t;
    d = scene(p);
    if (d < 0.001 || t > 50.0) break;
    t += d;
  }

  vec3 col = vec3(0.0);

  if (t < 50.0) {
    vec3 pos = ro + rd * t;
    vec3 nor = calcNormal(pos);

    // Base color from palette
    float h = pos.y / 6.0;
    vec3 baseColor;
    if (h < 0.33) baseColor = mix(u_color1, u_color2, h * 3.0);
    else if (h < 0.66) baseColor = mix(u_color2, u_color3, (h - 0.33) * 3.0);
    else baseColor = u_color3;

    col = applyLighting(pos, nor, rd, baseColor, u_glow);

    // Distance fog
    col = mix(col, u_background, 1.0 - exp(-0.02 * t * t));
  } else {
    // Background gradient
    col = u_background + rd.y * 0.05 * u_glow;
  }

  // Gamma correction
  col = pow(col, vec3(0.4545));

  gl_FragColor = vec4(col, 1.0);
}
