/**
 * JSON SCHEMA CONTRACTS
 *
 * These define the exact JSON formats for files generated at build-time.
 * Used by CHRONOS → IMAGINARIUM → ARCHITECTUS pipeline.
 */

/**
 * topology.json - Output from CHRONOS
 *
 * Contains the complete parsed codebase structure.
 */
export const TopologySchema = {
  $schema: "http://json-schema.org/draft-07/schema#",
  type: "object",
  required: ["version", "files", "commits", "tree"],
  properties: {
    version: { type: "string" },
    analyzedAt: { type: "string", format: "date-time" },
    files: {
      type: "array",
      items: {
        type: "object",
        required: ["path", "hash", "language"],
        properties: {
          path: { type: "string" },
          hash: { type: "string" },
          language: { type: "string" },
          complexity: { type: "number" },
          loc: { type: "number" },
          lastModified: { type: "string", format: "date-time" },
          author: { type: "string" }
        }
      }
    },
    commits: {
      type: "array",
      items: {
        type: "object",
        required: ["hash", "message", "author", "date"],
        properties: {
          hash: { type: "string" },
          message: { type: "string" },
          author: { type: "string" },
          date: { type: "string", format: "date-time" },
          filesChanged: { type: "array", items: { type: "string" } },
          insertions: { type: "number" },
          deletions: { type: "number" },
          isBugFix: { type: "boolean" },
          isFeature: { type: "boolean" },
          isMerge: { type: "boolean" },
          type: { type: "string" },
          scope: { type: "string" },
          isBreaking: { type: "boolean" },
          confidence: { type: "string", enum: ["high", "medium", "low"] }
        }
      }
    },
    tree: { type: "object" }, // FileTreeNode (recursive)
    hotspots: {
      type: "array",
      items: {
        type: "object",
        required: ["path", "churnRate", "complexity", "riskScore"],
        properties: {
          path: { type: "string" },
          churnRate: { type: "number" },
          complexity: { type: "number" },
          riskScore: { type: "number" }
        }
      }
    },
    repository: {
      type: "object",
      properties: {
        name: { type: "string" },
        remoteUrl: { type: "string" },
        currentBranch: { type: "string" },
        branchCount: { type: "number" },
        fileCount: { type: "number" },
        commitCount: { type: "number" },
        contributorCount: { type: "number" },
        languages: { type: "array", items: { type: "string" } },
        analyzedAt: { type: "string", format: "date-time" },
        headHash: { type: "string" }
      }
    },
    languageDistribution: {
      type: "array",
      items: {
        type: "object",
        required: ["language", "fileCount", "locTotal", "percentage"],
        properties: {
          language: { type: "string" },
          fileCount: { type: "number" },
          locTotal: { type: "number" },
          percentage: { type: "number" }
        }
      }
    },
    contributorSummary: {
      type: "object",
      properties: {
        totalContributors: { type: "number" },
        topContributor: { type: "string" },
        archetypeDistribution: { type: "object", additionalProperties: { type: "number" } }
      }
    },
    temporalCouplings: {
      type: "array",
      items: {
        type: "object",
        required: ["fileA", "fileB", "coChangeCount", "strength"],
        properties: {
          fileA: { type: "string" },
          fileB: { type: "string" },
          coChangeCount: { type: "number" },
          strength: { type: "number" }
        }
      }
    }
  }
} as const;

/**
 * palette.json - Output from IMAGINARIUM
 *
 * Contains the visual style derived from the codebase.
 */
export const PaletteSchema = {
  $schema: "http://json-schema.org/draft-07/schema#",
  type: "object",
  required: ["primary", "secondary", "accent", "background", "glow", "mood"],
  properties: {
    primary: { type: "string", pattern: "^#[0-9A-Fa-f]{6}$" },
    secondary: { type: "string", pattern: "^#[0-9A-Fa-f]{6}$" },
    accent: { type: "string", pattern: "^#[0-9A-Fa-f]{6}$" },
    background: { type: "string", pattern: "^#[0-9A-Fa-f]{6}$" },
    glow: { type: "string", pattern: "^#[0-9A-Fa-f]{6}$" },
    mood: { type: "string", enum: ["warm", "cool", "neutral"] }
  }
} as const;

/**
 * shaders/dendrite.glsl - Output from IMAGINARIUM
 *
 * This is a shader template, not JSON. Defined here for reference.
 */
export const SDFShaderTemplate = `
// Generated by IMAGINARIUM
// Seed: {{seed}}
// Style: {{style}}

uniform float time;
uniform vec3 branchColor;
uniform float complexity;

float sdf(vec3 p) {
  // Procedurally generated SDF function
  {{sdf_body}}
}

void main() {
  // Raymarching implementation
  {{raymarch_body}}
}
`;

/**
 * manifest.json - Output from OPERATUS
 *
 * Lists all generated assets for loading.
 */
export const ManifestSchema = {
  $schema: "http://json-schema.org/draft-07/schema#",
  type: "object",
  required: ["version", "checksum"],
  properties: {
    version: { type: "string" },
    checksum: { type: "string" },
    shaders: {
      type: "object",
      additionalProperties: { type: "string" }
    },
    palettes: {
      type: "object",
      additionalProperties: { type: "string" }
    },
    topology: { type: "string" }
  }
} as const;
